src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[UniqueEntity(fields: 'name', message: 'il y a dejà un trick avec ce nom')]
class Trick
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(length: 50, unique: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Photo::class, orphanRemoval: true, cascade: ['persist'])]
    #[Assert\Count(min: 1)]
    #[Assert\Valid]
    private Collection $photos;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class, orphanRemoval: true, cascade: ['persist'])]
    #[Assert\Valid]
    private Collection $videos;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 50, unique: true)]
    private ?string $slug = null;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setTrick($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getTrick() === $this) {
                $photo->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function getCover(): null|Photo
    {
        foreach ($this->photos as $photo) {
            if ($photo->isCover()) {
                return $photo;
            }
        }

        return null;
    }

    #[Assert\Callback]
    public function validateCover(ExecutionContextInterface $context, $payload)
    {
        $covers = $this->photos->filter(fn (Photo $photo) => $photo->isCover())->count();

        if (1 != $covers) {
            $context->buildViolation('Une image a déjà été selectionner en cover')
            ->addViolation();
        }
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    #[ORM\ManyToOne(inversedBy: 'videos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Trick $trick = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }

    public function getVideoId(): string
    {
        $url = $this->getLink();

        preg_match('/^https:\/\/www.youtube.com\/watch\?v=(?<id>[a-zA-Z0-9-_]+)/', $url, $matches);

        $embed = $matches['id'];

        return $embed;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Trick;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'w-100',
                ],
                'label' => 'Titre :',
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'w-100',
                    'rows' => '5',
                ],
                'label' => 'Description :',
            ])
            ->add('category', EntityType::class, [
                'choice_label' => 'name',
                'class' => Category::class,
                'attr' => [
                    'class' => 'w-25',
                ],
                'label' => 'Categorie :',
            ])

            ->add('photos', CollectionType::class, [
                'entry_type' => PhotoType::class,
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'error_bubbling' => false,
            ])
            ->add('videos', CollectionType::class, [
                'entry_type' => VideoType::class,
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'error_bubbling' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Form\TrickType;
use App\Repository\CommentRepository;
use App\Repository\TrickRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Manager\TrickManager;

class TrickController extends AbstractController
{
    public const COMMENTS_DISPLAY_STARTING = 10;
    public const COMMENTS_PER_LOADING = 10;

    #[Route('/addTrick', name: 'add_trick')]
    #[IsGranted('ROLE_USER')]
    public function addTrick(Request $request, TrickManager $trickManager): Response
    {
        $trick = new Trick();

        $form = $this->createForm(TrickType::class, $trick)->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trickManager->add($trick);
            $this->addFlash('success', 'Vous venez de créé un nouveau trick');

            return $this->redirectToRoute('home');
        }

        $trick->getPhotos()->clear();

        return $this->render('trick/addTrickNew.html.twig', ['form' => $form]);
    }

    #[Route('editTrick/{id}', name: 'edit_trick')]
    #[IsGranted('ROLE_USER')]
    public function editTrick(
        Trick $trick,
        TrickManager $trickManager,
        Request $request,
    ): Response {
        $form = $this->createForm(TrickType::class, $trick);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trickManager->update($trick);

            $this->addFlash('success', 'Vous venez de mettre à jour ce trick');

            return $this->redirectToRoute('home');
        }

        return $this->render('trick/editTrickNew.html.twig', [
            'form' => $form->createView(),
            'trick' => $trick,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('deleteTrick/{id}', name: 'delete_trick')]
    public function deleteTrick($id, TrickRepository $trickRepository): Response
    {
        $trickRepository->deleteTrick($id);

        return $this->redirectToRoute('home');
        $this->addFlash('success', 'Le trick a bien été supprimer.');
    }

    #[Route('trick/{slug}', name: 'show_trick')]
    public function showTrick(
        Trick $trick, 
        CommentRepository $commentRepository, 
        Request $request, 
        EntityManagerInterface $entityManager
    ): Response {

        // Comptabilise le nombres de commentaires en fonction du trick
        $totalAllComments = $commentRepository->countAllComments($trick);

        // On récupére les 10 premiers commentaires à afficher
        $commentsToDisplay = $commentRepository->getFirstComments(self::COMMENTS_DISPLAY_STARTING, $trick);

        /** @var User $user */
        $user = $this->getUser();

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment)->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAuthor($user);
            $comment->setCreatedAt(new \DateTimeImmutable('now'));
            $comment->setTrick($trick);

            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('trick/showTrickNew.html.twig', [
            'trick' => $trick,
            'form' => $form,
            'totalAllComments' => $totalAllComments,
            'commentsToDisplay' => $commentsToDisplay,
            'totalDisplayComments' => self::COMMENTS_DISPLAY_STARTING,
            'commentsPerLoading' => self::COMMENTS_PER_LOADING,
        ]);
    }

    #[Route('/getMoreComments/{id}', name: 'get_more_comment', methods: ['GET'])]
    public function getMoreComments(Trick $trick, Request $request, CommentRepository $commentRepository): Response
    {
        // On récupère l'ensemble des commentaires déjà charger sur la page
        $commentsAlreadyLoaded = $request->query->getInt('totalDisplayComments');
        
        // On récupère d'autre commentaires à afficher
        $commentsToDisplay = $commentRepository->getMoreComments(
            $commentsAlreadyLoaded, 
            self::COMMENTS_PER_LOADING, 
            $trick
        );

        return $this->render('comment/elements.html.twig', [
            'commentsToDisplay' => $commentsToDisplay,
        ]);
    }
}

templates/trick/_photo.html.twig
    {% if form.vars.data is not null and form.vars.data.name is not empty %}
        <img src="/uploads/{{form.vars.data.name}}" alt="..." class="img-thumbnail w-100 h-50">
    {% endif %}

    <div class="card w-100 d-flex justify-content-center mt-3">
        <div class="w-100 d-flex justify-content-center">
            <span class="w-25">
                {{ form_row(form.cover) }}
            </span>
            <span id="filePhotoEdit" class="w-25">
                <label for="{{ form.file.vars.id }}">
                <img class="editPhotoFile" src="{{ asset('build/images/icones/edit.svg') }}">
                </label>
                {{ form_widget(form.file) }}
            </span>
            <span id="filePhotoDelete" class="btn-remove w-25 text-center">
                <img class="deletePhotoFile text-center" src="{{ asset('build/images/icones/delete.svg') }}">
            </span>
        </div>
    </div>

templates/trick/_video.html.twig
<div class="item">
    {{ form_row(form.link) }}
    <div class="form-group d-flex justify-content-center">
        <button type="button" class="btn btn-danger btn-remove">Supprimer</button>
    </div>
</div>

templates/trick/addTrickNew.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'un trick{% endblock %}

{% block body %}

{% if is_granted("ROLE_USER") %}

<main class="pt-5 min-vh-100">
    <div class="container bg-white h-100 shadow rounded mb-5">
        {{ form_start(form) }}
        {{ form_errors(form) }}
        <div class="row d-flex justify-content-center pt-5">
            <div class="col-6">
                {{ form_row(form.name) }}
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-4">
            <div class="col-6">
                {{ form_row(form.description) }}
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-4">
            <div class="col-6">
                {{ form_row(form.category) }}
            </div>
        </div>

        <div class="d-flex justify-content-center">
            <button type="button" class="btn btn-primary btn-new" data-collection="#photos">Nouvelle photo</button>
        </div>

        <div 
            id="photos"
            class="row"
            data-prototype="{{ include("trick/_photo.html.twig", {form: form.photos.vars.prototype})|e("html_attr") }}" 
            data-index="{{ form.photos|length > 0 ? form.photos|last.vars.name + 1 : 0}}">
                {% for photo in form.photos %}
                    <div class="col-4">
                        {{ include("trick/_photo.html.twig", {form: photo}) }}
                    </div>
                {% endfor %}
        </div>
        {{ form_errors(form.photos) }}

        <div class="d-flex justify-content-center mt-4">
            <button type="button" class="btn btn-primary btn-new" data-collection="#videos">Nouvelle video</button>
        </div>

        <div 
            id="videos" 
            class="row"
            data-prototype="{{ include("trick/_video.html.twig", {form: form.videos.vars.prototype})|e("html_attr") }}" 
            data-index="{{ form.videos|length > 0 ? form.videos|last.vars.name + 1 : 0}}">
            <div class="d-flex justify-content-center">
            {% for video in form.videos %}
                <div class="col-4">
                    {{ include("trick/_video.html.twig", {form: video}) }}
                </div>
            {% endfor %}
            </div>
        </div>
        {{ form_errors(form.videos) }}

        <div class="row d-flex justify-content-center mt-5 mb-5">
            <div class="col-6 mb-5 d-flex justify-content-center">
                <button class="btn btn-primary">Valider</button>
            </div>
        </div>
        {{ form_end(form, {render_rest: true}) }}
    </div>
</main>

{% else %}

    <h3>Vous devez être connecter pour pouvoir ajouter une figure</h3>

{% endif %}


{% endblock %}

templates/trick/editTrickNew.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le {{ trick.name }}{% endblock %}

{% block body %}

<main class="pt-5 min-vh-100" id="mainEditTrick">
    <div class="container bg-white h-100 shadow rounded mb-5">

        <div class="row no-gutters h-100">
            
            <div id="coverEdit" class="col-12 position-relative ratio ratio-16x9">
                <img src="{{ asset("uploads/" ~ trick.cover.name) }}" alt="" class="rounded-top ratio ratio-16x9 z-1 w-100 position-absolute top-0 left-0">
                <h1 class="z-2 m-0 flex-shrink-0  d-flex justify-content-center align-items-center">{{trick.name}}</h1>
            </div>

        </div>

        {% if is_granted("ROLE_USER") %}
    
        {{ form_start(form) }}
            {{ form_widget(form._token) }}

            {{ form_errors(form) }}

        <div class="d-flex w-100 mt-4" id="mediaEditTrick" >
            <div id="photosEdit" class="d-flex w-50 h-100 me-2 flex-wrap justify-content-center">
                <div 
                    id="photos"
                    class="row d-flex justify-content-center"
                    data-prototype="{{ include("trick/_photo.html.twig", {form: form.photos.vars.prototype})|e("html_attr") }}" 
                    data-index="{{ form.photos|length > 0 ? form.photos|last.vars.name + 1 : 0}}">

                    {% for photo in form.photos %}
                        <div id="imageInput" class="col-4 mt-3">
                            {{ include("trick/_photo.html.twig", {form: photo}) }}
                        </div>
                    {% endfor %}
                </div>
                {{ form_errors(form.photos) }}
            </div>

            <div id="videosEdit" class="d-flex w-50 h-100 ms-2 flex-wrap justify-content-center">
    
                <div 
                    id="videos" 
                    class="row d-flex justify-content-center"
                    data-prototype="{{ include("trick/_video.html.twig", {form: form.videos.vars.prototype})|e("html_attr") }}" 
                    data-index="{{ form.videos|length > 0 ? form.videos|last.vars.name + 1 : 0}}">
                    {% for video in form.videos %}
                        <div id="urlVideoInput" class="col-4 mt-3">
                            {{ include("trick/_video.html.twig", {form: video}) }}
                        </div>
                    {% endfor %}
                </div>
                {{ form_errors(form.videos) }}
            </div>
        </div>

        <div class="row" id="addMedias">
            <div class="col-6 d-flex justify-content-center">
                <button type="button" class="btn btn-primary btn-new  mt-4" data-collection="#photos">Nouvelle photo</button>
            </div>
            <div class="col-6 d-flex justify-content-center">
                <button type="button" class="btn btn-primary btn-new mt-4" data-collection="#videos">Nouvelle video</button>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-5">
            <div class="col-lg-6 col-md-10 col-sm-10">
                {{ form_row(form.name) }}</br>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-4">
            <div class="col-lg-6 col-md-10 col-sm-10">
                {{ form_row(form.description) }}</br>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-2">
            <div class="col-lg-6 col-md-10 col-sm-10">
                {{ form_row(form.category) }}</br>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-2 mb-5">
            <div class="col-6 mb-5 d-flex justify-content-center">
                <button class="btn btn-success mt-4">Valider</button>
            </div>
        </div>
        
        {{ form_end(form, {render_rest: false}) }}

        {% else %}

        <h3>Vous devez être connecter pour pouvoir modifier la figure</h3>

        {% endif %}

    </div>
</main>

{% endblock %}

templates/trick/elements.html.twig
{% for trick in tricksToDisplay %}
    <div class="card mb-4 ms-3 me-3 cardTrick">
        <img class="img-fluid h-75" src="{{ asset("uploads/" ~ trick.cover.name) }}" alt="">
        <div class="card-body d-flex justify-content-between">
            <div class="titleTrick w-75">
                <h5 class="card-title"><a class="text-dark" href="{{ path('show_trick', {slug: trick.slug}) }}">{{trick.name}}</a></h5>
            </div>
            {% if is_granted("ROLE_USER") %}
            <div class="optionTrick w-25">
                <span><a href="{{ path('edit_trick', {id: trick.id}) }}"><img class="editIcon" src="{{ asset('build/images/icones/edit.svg') }}"></a></span>
                <span data-bs-toggle="modal" data-bs-target="#deleteModal"><img class="deleteIcon" src="{{ asset('build/images/icones/delete.svg') }}"></span>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Suppression d'un trick</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Êtes-vous sûr de vouloir supprimer ce trick : "{{ trick.name }}"</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                    <button type="button" class="btn btn-primary"><a class="text-white text-decoration-none" href="{{ path('delete_trick', {id: trick.id}) }}">Supprimer</a></button>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/trick/showTrickNew.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ trick.name }}{% endblock %}

{% block body %}

<main class="pt-5 min-vh-100" id="mainShowTrick">
    <div class="container bg-white h-100 shadow rounded mb-5">
        <div class="row no-gutters h-100">
        <div class="col-12 position-relative ratio ratio-16x9">
            <img src="{{ asset("uploads/" ~ trick.cover.name) }}" alt="" class="rounded-top ratio ratio-16x9 z-1 w-100 position-absolute top-0 left-0">
            <h1 class="z-2 m-0 flex-shrink-0  d-flex justify-content-center align-items-center">Super figure de la mort</h1>
        </div>
    </div>

    <div id="mediaTricks" class="d-flex w-100 mt-4">
            <div class="d-flex w-50 h-100 flex-wrap justify-content-center mediasImages">
            {% for photo in trick.photos %}
                    <div class="mt-1">
                        <a class="d-block overlay" data-fslightbox="lightbox-basic" href="{{ asset("uploads/" ~ photo.name ) }}" >
                            <img id="imageGallery" src ="{{ asset("uploads/" ~ photo.name ) }}">
                        </a>
                    </div>
            {% endfor %}
            </div>

            <div class="d-flex w-50 h-100 flex-wrap justify-content-center mediasVideos">
            {% for video in trick.videos %}
                    <div class="me-2">
                        <a data-fslightbox="gallery" href="{{ video.link }}">
                            <iframe src="https://www.youtube.com/embed/{{ video.videoId }}">
                            </iframe>
                        </a>
                    </div>
            {% endfor %}
            </div>
    </div>

    <div class="row mt-5">
        <div class="d-flex justify-content-center">
            <div class="col-8">
                <p class="text-start">{{trick.description}}</p>
            </div>
        </div>
        <div class="d-flex justify-content-center text-center">
            <p class="me-3"><small class="text-muted">{{trick.category.name}}</small></p>
            <p class="me-3"><small class="text-muted">Crée le {{trick.createdAt|date('d/m/Y')}}</small></p>
            <p class="me-3"><small class="text-muted">Crée par {{trick.author}}</small></p>
            <p class=""><small class="text-muted">Mis à jour le {{trick.updatedAt|date('d/m/Y')}}</small></p>
        </div> 
    </div>
    {% if is_granted("ROLE_USER") %}
    <div class="row border-top border-bottom me-5 ms-5 pt-5 pb-5">
        <div class="col-12 d-flex justify-content-center formCommentary">
        {{ form_start(form) }}
            <div class="form-outline mb-4 me-4 d-flex justify-content-center addCommentary">
                <div class="w-100">
                    {{ form_widget(form.message, {'attr': {'class': 'form-control text-center'}}) }}
                </div>
                <div class="w-50 buttonCommentary">
                    <button type="submit" class="btn btn-primary ms-4 w-100">Laisser un commentaire</button>
                </div>
            </div>

        {{ form_end(form) }}
        </div>
    </div>
    {% endif %}
    <div class="row mb-4">
        <section id="allComments" class="row mt-5 d-flex justify-content-center p-0 m-0">
            <div class="col-lg-8 col-md-10 col-sm-12 d-flex flex-column justify-content-center">
                {{ include ('comment/elements.html.twig') }}
            </div>
        </section>
    </div>
    <div class="row">
        {% if totalAllComments > totalDisplayComments %}
        <section class="d-flex justify-content-center" id="moreComments">
            <button class="btn btn-primary mt-5" id="loadMoreComments">Plus de commentaires</button>
            <input type="hidden" id="totalDisplayComments" value="{{ totalDisplayComments }}">
            <input type="hidden" id="totalAllComments" value="{{ totalAllComments }}">
            <input type="hidden" id="commentsPerLoading" value="{{ commentsPerLoading }}">
            <input type="hidden" id="idTrick" value="{{ trick.id }}">
        </section>
        {% endif %}
    </div>
  </div>
</main>

{% endblock %}